name: Check My Status
on: push
jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # Install npm dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run in Chrome
        uses: cypress-io/github-action@v6
        with:
          command: npm run ui-regression-chrome
          browser: chrome
      - name: Uploading artifact
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: cypress-execution-report
          path: cypress/reports/html
          retentiondays: 30
      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_USERNAME: Test Automation
          SLACK_TITLE: Regression Test Report
          SLACK_MESSAGE: "New changes :rocket:"
          SLACK_COLOR: ${{ job.status }}
